### ISSUE TITLE
Implement first batch of unit alignment between P06 units and QUDT units

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P06#11]
See https://github.com/qudt/qudt-public-repo/issues/30

**Comment by gwemon** [comment]
As of today 130 P06 units have been aligned to QUDT units.

**Comment by dr-shorthair** [comment]
Might be worth also adding the UCUM codes. Probably as a `skos:notation`. 

UCUM spec is here: https://ucum.org/ucum.html 
And there is a UCUM-based quantity conversion service API here: https://ucum.nlm.nih.gov/ucum-service.html
(and a UI here: https://ucum.nlm.nih.gov/ucum-lhc/demo.html )

**Comment by dr-shorthair** [comment]
You might also add requests for the 'missing' units in QUDT as issues. e.g. https://github.com/qudt/qudt-public-repo/issues/221

**Comment by dr-shorthair** [comment]
If QUDT had the complete set, would there be potential to retire P06? else retain it just to capture the links to the other NVS vocabs.

**Comment by dr-shorthair** [comment]
FWIW I've created a SWEET-QUDT alignment graph - see https://github.com/ESIPFed/sweet/pull/221

**Comment by dr-shorthair** [comment]
And also catalogued the ones from SWEET that are missing from QUDT - https://github.com/qudt/qudt-public-repo/issues/231

**Comment by gwemon** [comment]
> If QUDT had the complete set, would there be potential to retire P06?
> else retain it in order to capture the links to the other NVS vocabs.

@dr-shorthair No I don't think so. P06 is part of a number of well established data workflows and file formats, and it would be more effort to retire it than it is to maintain it. I see QUDT as being a useful external reference for us and also, hopefully, a source of community developed tools.

**Comment by dr-shorthair** [comment]
Fair enough. That was what I expected. But I think we can make the alignment closer.

**Comment by gwemon** [comment]
> Fair enough. That was what I expected. But I think we can make the alignment closer.

Yes I completely agree. This was a starter. I'll try and contribute more as soon as I have a bit more time to do so.

**Comment by dr-shorthair** [comment]
@gwemon I will assist with this. 
I believe this is the list that does not (yet) have QUDT matches: 
[P06-qudt-missing-ucum.txt](https://github.com/nvs-vocabs/P06/files/5442762/P06-qudt-missing-ucum.txt)

**Comment by dr-shorthair** [comment]
These seven can be matched to units that already exist in the QUDT vocabulary: 

- http://vocab.nerc.ac.uk/collection/P06/current/SQM2/	http://qudt.org/vocab/unit/M2-PER-SEC2
- http://vocab.nerc.ac.uk/collection/P06/current/UCMS/	http://qudt.org/vocab/unit/CentiM2-PER-SEC 
- http://vocab.nerc.ac.uk/collection/P06/current/UCNT/	http://qudt.org/vocab/unit/NUM
- http://vocab.nerc.ac.uk/collection/P06/current/UNSM/	http://qudt.org/vocab/unit/N-PER-M2
- http://vocab.nerc.ac.uk/collection/P06/current/UWCM/	http://qudt.org/vocab/unit/W-PER-M3
- http://vocab.nerc.ac.uk/collection/P06/current/WAPK/	http://qudt.org/vocab/unit/W-PER-M-K
- http://vocab.nerc.ac.uk/collection/P06/current/WMSS/	http://qudt.org/vocab/unit/W-PER-M2-SR

**Comment by gwemon** [comment]
The first 2 QUDT URLs http://qudt.org/vocab/unit/M2-PER-SEC2 and http://qudt.org/vocab/unit/CentiM2-PER-SEC are not found. I have added the remaining 5 to the NVS. They will be live shortly after 0200UT.

**Comment by dr-shorthair** [comment]
OK - I've added them to the spreadsheet here https://github.com/qudt/qudt-public-repo/issues/268#issuecomment-721424132

**Comment by dr-shorthair** [comment]
> The first 2 QUDT URLs http://qudt.org/vocab/unit/M2-PER-SEC2 and http://qudt.org/vocab/unit/CentiM2-PER-SEC are not found. 

They are all OK now

**Comment by gwemon** [comment]
Mappings added to https://vocab.nerc.ac.uk/collection/P06/current/UCMS and http://vocab.nerc.ac.uk/collection/P06/current/SQM2
It will be live on the NVS shortly after 0700 UT tomorrow morning
