### ISSUE TITLE
NTR: Request for P06 Square micrometre 

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#13]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Square micrometre  <p><b>Definition</b><p> Square micrometre (µm2) is a unit in the category of Area. It has a dimension of L2 where L is length. It can be converted to the corresponding standard SI unit m2 by multiplying its value by a factor of 1E-012.<p><H2> Optional </H2><p><b>Sources/references</b><p> http://dbpedia.org/describe/?url=http%3A%2F%2Fdbpedia.org%2Fresource%2FSquare_micrometre&sid=128020<p> <b>Synonym or acronym (AltLabel)</b><p> square micrometres, square micrometer, square micrometers, µm2<p><b>Mapping to other terminologies </b><p> http://vocab.nerc.ac.uk/collection/P06/current/UMIC/<p>

**Comment by gwemon** [comment]
This term has been added to the NVS. It will be published today as http://vocab.nerc.ac.uk/collection/P06/current/SQUM/

**Comment by dr-shorthair** [comment]
UCUM Code: `um2`
