### ISSUE TITLE
M2SX has incorrect mapping to QUDT

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#15]
http://vocab.nerc.ac.uk/collection/P06/current/M2SX/ is mapped to http://qudt.org/vocab/unit/CentiM2-SEC 
Should be http://qudt.org/vocab/unit/M2-SEC (which does yet exist in QUDT)

**Comment by gwemon** [comment]
Thank you @dr-shorthair. Corrected in the database. It will be live after our next refresh in about 6h.
