### ISSUE TITLE
NTR: Request for P06 Millibecquerels per cubic metre

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#16]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Millibecquerels per cubic metre <p><b>Definition</b><p> One radioactive disintegration per thousand seconds from an SI standard unit of volume. Equivalent Microbecquerels per litre.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-672<p> <b>Synonym or acronym (AltLabel)</b><p> mBq/m^3<p>

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/P06/current/MBQM/ created

**Comment by dr-shorthair** [comment]
UCUM Code: `mBq/m3`
