### ISSUE TITLE
NTR: Request for P06 Atoms per kilogram

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Atoms per kilogram <p><b>Definition</b><p> Unit based on one atom in a SI standard unit of mass.<p><H2> Optional </H2><p><b>Synonym or acronym (AltLabel)</b><p> at/kg<p>

**Comment by dr-shorthair** [comment]
UCUM Code: `{atom}.kg-1`

**Comment by danibodc** [comment]
New P06 term has now been created:
http://vocab.nerc.ac.uk/collection/P06/current/ATKG/

ATKG Atoms per kilogram
Description: Unit based on one atom in a SI standard unit of mass.

This has also been mapped to the following P24 dimension term:
http://vocab.nerc.ac.uk/collection/P24/current/MOLPMASS/ 

MOLPMASS [amount of substance]/[mass]
The fundamental dimension of the number of atoms per the fundamental dimension of heaviness

Many thanks.
