### ISSUE TITLE
QUDT additions needed to support P06 alignments

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#18]
P06 item | UCUM code | QUDT item to be requested
--- | --- | ---
<http://vocab.nerc.ac.uk/collection/P06/current/BSM3/> | Bq.s.m-3 | unit:BQ-SEC-PER-M3
<http://vocab.nerc.ac.uk/collection/P06/current/DBPY/> | dbar.a-1 | unit:DeciBAR-PER-YR
<http://vocab.nerc.ac.uk/collection/P06/current/DCPY/> | Cel.a-1 | unit:DEG_C-PER-YR
<http://vocab.nerc.ac.uk/collection/P06/current/DGPM/> | deg.m-1 | unit:DEG-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/DKM2/> | Cel.kg.m-2 | unit:DEG_C-KiloGM-PER-M2
<http://vocab.nerc.ac.uk/collection/P06/current/DKPM/> | K.m-1 | unit:K-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/FGKG/> | fg.kg-1 | unit:FemtoGM-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/FGPL/> | fg.L-1 | unit:FemtoGM-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/FMKG/> | fmol.kg-1 | unit:FemtoMOL-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/GQCY/> | g.cm-2.a-1 | unit:GM-PER-CentiM2-YR
<http://vocab.nerc.ac.uk/collection/P06/current/HPAH/> | hPa.h-1 | unit:HectoPA-PER-HR
<http://vocab.nerc.ac.uk/collection/P06/current/JCMH/> | J.cm-2.d-1 | unit:J-PER-CentiM2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/JKGK/> | J.kg-1.K-1 | unit:J-PER-KiloGM-K
<http://vocab.nerc.ac.uk/collection/P06/current/KGAK/> | kg.km-2 | unit:KiloGM-PER-KiloM2
<http://vocab.nerc.ac.uk/collection/P06/current/KGMH/> | kg.m-1.h-1 | unit:KiloGM-PER-M-HR
<http://vocab.nerc.ac.uk/collection/P06/current/KGNM/> | nmol.kg-1 | unit:NanoMOL-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/KGPM/> | pmol.kg-1 | unit:PicoMOL-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/KGS2/> | kg2.s-2 | unit:KiloGM2-PER-SEC2
<http://vocab.nerc.ac.uk/collection/P06/current/KGUM/> | umol.kg-1 | unit:MicroMOL-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/KLSQ/> | K2 | unit:K2
<http://vocab.nerc.ac.uk/collection/P06/current/KMDY/> | km.d-1 | unit:KiloM-PER-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/KMPS/> | kg.m-1.s-1 | unit:KiloGM-PER-M-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/KMSS/> | K.m2.kg-1.s-1 | unit:K-M2-PER-KiloGM-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/KMTS/> | K.m.s-1 | unit:K-M-PER-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/KMTX/> | K.m | unit:K-M
<http://vocab.nerc.ac.uk/collection/P06/current/KPAS/> | K.Pa.s-1 | unit:K-PA-PER-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/KPMT/> | K.m-1 | unit:K-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/KSP2/> | kg.m-2.s-1 | unit:KiloGM-PER-M2-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/KSP3/> | kg.m-3.s-1 | unit:KiloGM-PER-M3-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/KSXX/> | K.s | unit:K-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/LPUM/> | L.umol-1 | unit:L-PER-MicroMOL
<http://vocab.nerc.ac.uk/collection/P06/current/M2HD/> | m2.Hz-1.deg-1 | unit:M2-PER-HZ-DEG
<http://vocab.nerc.ac.uk/collection/P06/current/M2MM/> | mol.m-2.s-1.m-1 | unit:MOL-PER-M2-SEC-M
<http://vocab.nerc.ac.uk/collection/P06/current/M2MS/> | mol.m-2.s-1 | unit:MOL-PER-M2-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/M2RD/> | m2.s.rad-1 | unit:M2-SEC-PER-RAD
<http://vocab.nerc.ac.uk/collection/P06/current/M2S2/> | m-2.s-1 | unit:PER-M2-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/M2SR/> | mol.m-2.s-1.m-1.sr-1 | unit:MOL-PER-M2-SEC-M-SR
<http://vocab.nerc.ac.uk/collection/P06/current/M3PS/> | m-3.s-1 | unit:PER-M3-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/M3SR/> | mol.m-2.s-1.sr-1 | unit:MOL-PER-M2-SEC-SR
<http://vocab.nerc.ac.uk/collection/P06/current/M4S1/> | m4.s-1 | unit:M4-PER-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/MBPG/> | mBq.g-1 | unit:MilliBQ-PER-GM
<http://vocab.nerc.ac.uk/collection/P06/current/MBQF/> | mBq.m-2.d-1 | unit:MilliBQ-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/MBQK/> | mBq.kg-1 | unit:MilliBQ-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/MCMD/> | mmol.m-3.d-1 | unit:MilliMOL-PER-M3-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/MGLH/> | ug.L-1.h-1 | unit:MicroGM-PER-L-HR
<http://vocab.nerc.ac.uk/collection/P06/current/MGPM/> | mGal.mo-1 | unit:MilliGAL-PER-MO
<http://vocab.nerc.ac.uk/collection/P06/current/MGSQ/> | mg.m-2.h-1 | unit:MilliGM-PER-M2-HR
<http://vocab.nerc.ac.uk/collection/P06/current/MLM2/> | mol.m-2 | unit:MOL-PER-M2
<http://vocab.nerc.ac.uk/collection/P06/current/MM3S/> | mol.m-3.s-1 | unit:MOL-PER-M3-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/MMCM/> | mmol.m-3 | unit:MilliMOL-PER-M3
<http://vocab.nerc.ac.uk/collection/P06/current/MMOM/> | mmol.mol-1 | unit:MilliMOL-PER-MOL
<http://vocab.nerc.ac.uk/collection/P06/current/MMSM/> | mmol.m-2 | unit:MilliMOL-PER-M2
<http://vocab.nerc.ac.uk/collection/P06/current/MPGH/> | mol.g-1.h-1 | unit:MOL-PER-GM-HR
<http://vocab.nerc.ac.uk/collection/P06/current/MPMX/> | mol.mol-1 | unit:MOL-PER-MOL
<http://vocab.nerc.ac.uk/collection/P06/current/MPYR/> | m.a-1 | unit:M-PER-YR
<http://vocab.nerc.ac.uk/collection/P06/current/MRAD/> | mRAD.h-1 | unit:MilliRAD_R-PER-HR
<http://vocab.nerc.ac.uk/collection/P06/current/MSMD/> | mL.m-2.d-1 | unit:MilliL-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/MSPM/> | mS.m-1 | unit:MilliS-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/MWNM/> | mW.m-2.nm-1 | unit:MilliW-PER-M2-NanoM
<http://vocab.nerc.ac.uk/collection/P06/current/MWNS/> | mW.m-2.nm-1.sr-1 | unit:MilliW-PER-M2-NanoM-SR
<http://vocab.nerc.ac.uk/collection/P06/current/MWSR/> | mW.cm-2.um-1.sr-1 | unit:MilliW-PER-CentiM2-MicroM-SR
<http://vocab.nerc.ac.uk/collection/P06/current/NBHG/> | {#}.hg-1 | unit:NUM-PER-HectoGM
<http://vocab.nerc.ac.uk/collection/P06/current/NBMG/> | {#}.mg-1 | unit:NUM-PER-MilliGM
<http://vocab.nerc.ac.uk/collection/P06/current/NCUM/> | N.m-3 | unit:N-PER-M3
<http://vocab.nerc.ac.uk/collection/P06/current/NHTR/> | {#}.har-1 | unit:NUM-PER-HA
<http://vocab.nerc.ac.uk/collection/P06/current/NMCH/> | nmol.cm-3.h-1 | unit:NanoMOL-PER-CentiM3-HR
<http://vocab.nerc.ac.uk/collection/P06/current/NMGH/> | nmol.ug-1.h-1 | unit:NanoMOL-PER-MicroGM-HR
<http://vocab.nerc.ac.uk/collection/P06/current/NMMD/> | nmol.umol-1.d-1 | unit:NanoMOL-PER-MicroMOL-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/NMMM/> | nmol.umol-1 | unit:NanoMOL-PER-MicroMOL
<http://vocab.nerc.ac.uk/collection/P06/current/NOPH/> | {#}.h-1 | unit:NUM-PER-HR
<http://vocab.nerc.ac.uk/collection/P06/current/NOPM/> | {#}.m-1 | unit:NUM-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/NPKM/> | {#}.km-2 | unit:NUM-PER-KiloM2
<http://vocab.nerc.ac.uk/collection/P06/current/NSQD/> | nmol.m-2.d-1 | unit:NanoMOL-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/PAM2/> | Pa.m.s-2 | unit:PA-M-PER-SEC2
<http://vocab.nerc.ac.uk/collection/P06/current/PAMS/> | Pa.m.s-1 | unit:PA-M-PER-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/PAMT/> | Pa.m | unit:PA-M
<http://vocab.nerc.ac.uk/collection/P06/current/PG01/> | g-1 | unit:PER-GM
<http://vocab.nerc.ac.uk/collection/P06/current/PGKG/> | pg.kg-1 | unit:PicoGM-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/PGPG/> | pg.g-1 | unit:PicoGM-PER-GM
<http://vocab.nerc.ac.uk/collection/P06/current/PGPL/> | pg.L-1 | unit:PicoGM-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/PMLD/> | pmol.L-1.d-1 | unit:PicoMOL-PER-L-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/PMPS/> | m-1.s-1 | unit:PER-M-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/PMSC/> | ms-1 | unit:PER-MilliSEC
<http://vocab.nerc.ac.uk/collection/P06/current/PMSR/> | m-1.sr-1 | unit:PER-M-SR
<http://vocab.nerc.ac.uk/collection/P06/current/PPPS/> | Pa-1.s-1 | unit:PER-PA-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/PPS2/> | Pa2.s-2 | unit:PA2-PER-SEC2
<http://vocab.nerc.ac.uk/collection/P06/current/PSTR/> | sr-1 | unit:PER-SR
<http://vocab.nerc.ac.uk/collection/P06/current/PUML/> | umol-1.L-1 | unit:PER-MicroMOL-L
<http://vocab.nerc.ac.uk/collection/P06/current/PWAV/> | pW.cm-2.L-1 | unit:PicoW-PER-CentiM2-L
<http://vocab.nerc.ac.uk/collection/P06/current/SCPM/> | s.m-1 | unit:SEC-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/SMPG/> | m2.g-1 | unit:M2-PER-GM
<http://vocab.nerc.ac.uk/collection/P06/current/SQCC/> | cm2.cm-3 | unit:CentiM2-PER-CentiM3
<http://vocab.nerc.ac.uk/collection/P06/current/UATM/> | uatm | unit:MicroATM
<http://vocab.nerc.ac.uk/collection/P06/current/UBQL/> | Bq.L-1 | unit:BQ-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UCCM/> | um3.m-3 | unit:MicroM3-PER-M3
<http://vocab.nerc.ac.uk/collection/P06/current/UCKA/> | cm.ka-1 | unit:CentiM-PER-KiloYR
<http://vocab.nerc.ac.uk/collection/P06/current/UCNL/> | {#}.nL-1 | unit:NUM-PER-NanoL
<http://vocab.nerc.ac.uk/collection/P06/current/UCPL/> | {#}.L-1 | unit:NUM-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UCPS/> | {#}.s-1 | unit:NUM-PER-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/UCSS/> | K2.s-1 | unit:K2-PER-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/UCUL/> | {#}.uL-1 | unit:NUM-PER-MicroL
<http://vocab.nerc.ac.uk/collection/P06/current/UCUM/> | um3.mL-1 | unit:MicroM3-PER-MilliL
<http://vocab.nerc.ac.uk/collection/P06/current/UGDC/> | mg.m-3.d-1 | unit:MilliGM-PER-M3-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UGDX/> | mg.m-2.d-1 | unit:MilliGM-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UGGR/> | ug.g-1 | unit:MicroGM-PER-GM
<http://vocab.nerc.ac.uk/collection/P06/current/UGLH/> | mg.m-3.h-1 | unit:MilliGM-PER-M3-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UGM3/> | ug.m-3.h-1 | unit:MicroGM-PER-M3-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UGPG/> | pg | unit:PicoGM
<http://vocab.nerc.ac.uk/collection/P06/current/UGPM/> | uGal.m-1 | unit:MicroGAL-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/UM2S/> | umol.m-2.s-1 | unit:MicroMOL-PER-M2-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/UMBQ/> | mBq.L-1 | unit:MilliBQ-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UMCU/> | um3 | unit:MicroM3
<http://vocab.nerc.ac.uk/collection/P06/current/UMDX/> | mmol.m-2.d-1 | unit:MilliMOL-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UMFX/> | umol.m-2.h-1 | unit:MicroMOL-PER-M2-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UMHZ/> | m2.Hz-1 | unit:M2-PER-HZ
<http://vocab.nerc.ac.uk/collection/P06/current/UMMD/> | um.L-1.d-1 | unit:MicroM-PER-L-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UMMH/> | umol.L-1.h-1 | unit:MicroMOL-PER-L-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UMNS/> | m-1.nm-1.sr-1 | unit:PER-M-NanoM-SR
<http://vocab.nerc.ac.uk/collection/P06/current/UMNX/> | m-1.nm-1 | unit:PER-M-NanoM
<http://vocab.nerc.ac.uk/collection/P06/current/UMPM/> | umol.mol-1 | unit:MicroMOL-PER-MOL
<http://vocab.nerc.ac.uk/collection/P06/current/UMSG/> | m2.g-1{dry} | ~unit:M2-PER-GM
<http://vocab.nerc.ac.uk/collection/P06/current/UMTB/> | m2.Hz | unit:M2-HZ
<http://vocab.nerc.ac.uk/collection/P06/current/UMTC/> | m2.Hz2 | unit:M2-HZ2
<http://vocab.nerc.ac.uk/collection/P06/current/UMTD/> | m2.Hz3 | unit:M2-HZ3
<http://vocab.nerc.ac.uk/collection/P06/current/UMTE/> | m2.Hz4 | unit:M2-HZ4
<http://vocab.nerc.ac.uk/collection/P06/current/UMTN/> | m2.Hz-2 | unit:M2-PER-HZ2
<http://vocab.nerc.ac.uk/collection/P06/current/UMUB/> | umol.umol-1.d-1 | unit:MicroMOL-PER-MicroMOL-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UNAH/> | {#}.h-1 | unit:NUM-PER-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UNBQ/> | nBq.L-1 | unit:NanoBQ-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UNDX/> | {#}.m-2.d-1 | unit:NUM-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UNGL/> | ng.L-1 | unit:NanoGM-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UNID/> | ng.d-1 | unit:NanoGM-PER-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UNMD/> | nmol.L-1.d-1 | unit:NanoMOL-PER-L-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UNMH/> | nmol.L-1.h-1 | unit:NanoMOL-PER-L-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UNPG/> | {#}.g-1 | unit:NUM-PER-GM
<http://vocab.nerc.ac.uk/collection/P06/current/UNPI/> | ng | unit:NanoGM
<http://vocab.nerc.ac.uk/collection/P06/current/UNUL/> | ng.ul-1 | unit:NanoGM-PER-MicroL
<http://vocab.nerc.ac.uk/collection/P06/current/UPAM/> | pA.umol-1.L-1 | unit:PicoA-PER-MicroMOL-L
<http://vocab.nerc.ac.uk/collection/P06/current/UPCC/> | Cel.m-1 | unit:DEG_C-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/UPCD/> | %.d-1 | unit:PERCENT-PER-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UPCH/> | %.h-1 | unit:PERCENT-PER-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UPCW/> | %.wk-1 | unit:PERCENT-PER-WK
<http://vocab.nerc.ac.uk/collection/P06/current/UPFM/> | fmol.L-1 | unit:FemtoMOL-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UPMA/> | pmol.m-3 | unit:PicoMOL-PER-M3
<http://vocab.nerc.ac.uk/collection/P06/current/UPMD/> | pmol.m-2.d-1 | unit:PicoMOL-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UPMH/> | pmol.L-1.h-1 | unit:PicoMOL-PER-L-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UPML/> | pmol.L-1 | unit:PicoMOL-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UPMM/> | {#}.m-3 | unit:NUM-PER-M3
<http://vocab.nerc.ac.uk/collection/P06/current/UPMS/> | {#}.m-2 | unit:NUM-PER-M2
<http://vocab.nerc.ac.uk/collection/P06/current/UPOP/> | %.m-1 | unit:PERCENT-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/UPOX/> | umol.L-1 | unit:MicroMOL-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UPSS/> | s-2 | unit:PER-SEC2
<http://vocab.nerc.ac.uk/collection/P06/current/UPTH/> | [ppth].h-1 | unit:PPTH-PER-HR
<http://vocab.nerc.ac.uk/collection/P06/current/UPVT/> | pmol.m-3.s-1 | unit:PicoMOL-PER-M3-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/UPVW/> | pmol.m-1.W-1.s-1 | unit:PicoMOL-PER-M-W-SEC
<http://vocab.nerc.ac.uk/collection/P06/current/USUM/> | um2.mL-1 | unit:MicroM-PER-MilliL
<http://vocab.nerc.ac.uk/collection/P06/current/UTRV/> | [pptr]{vol} | ~unit:PPTR
<http://vocab.nerc.ac.uk/collection/P06/current/UUBQ/> | uBq.L-1 | unit:MicroBQ-PER-L
<http://vocab.nerc.ac.uk/collection/P06/current/UUDX/> | ug.m-2.d-1 | unit:MicroGM-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UUPH/> | [pH] | https://github.com/qudt/qudt-public-repo/issues/267
<http://vocab.nerc.ac.uk/collection/P06/current/UUUD/> | umol.m-2.d-1 | unit:MicroMOL-PER-M2-DAY
<http://vocab.nerc.ac.uk/collection/P06/current/UVAY/> | {#}.cm-2.ka-1 | unit:NUM-PER-CentiM-KiloYR
<http://vocab.nerc.ac.uk/collection/P06/current/UWBQ/> | uBq.kg-1 | unit:MicroBQ-PER-KiloGM
<http://vocab.nerc.ac.uk/collection/P06/current/UWNM/> | W.m-2.nm-1 | unit:W-PER-M2-NanoM
<http://vocab.nerc.ac.uk/collection/P06/current/UWNS/> | W.m-2.nm-1.sr-1 | unit:W-PER-M2-NanoM-SR
<http://vocab.nerc.ac.uk/collection/P06/current/WAPM/> | W.m-1 | unit:W-PER-M
<http://vocab.nerc.ac.uk/collection/P06/current/WM2M/> | W.m-2.m-1 | unit:W-PER-M2-M
<http://vocab.nerc.ac.uk/collection/P06/current/WM2S/> | W.m-2.m-1.sr-1 | unit:W-PER-M2-M-SR
<http://vocab.nerc.ac.uk/collection/P06/current/WMSW/> | W.m-2.m.sr-1 | unit:W-M-PER-M2-SR
<http://vocab.nerc.ac.uk/collection/P06/current/WSMM/> | W.s.m-2 | unit:W-SEC-PER-M2

**Comment by dr-shorthair** [comment]
Here's the RDF if you can use it
[P06-qudt-requests.ttl](https://github.com/nvs-vocabs/P06/files/5451091/P06-qudt-requests.ttl.txt)

**Comment by dr-shorthair** [comment]
I've just dropped a table of requests here: https://github.com/qudt/qudt-public-repo/issues/268#issuecomment-718375632

**Comment by dr-shorthair** [comment]
The missing items are now merged into main QUDT - https://github.com/qudt/qudt-public-repo/pull/292 
So I think you an add these `owl:sameAs` links into P06 - [P06-qudt-requests.ttl](https://github.com/nvs-vocabs/P06/files/5462525/P06-qudt-requests.ttl.txt)

**Comment by stuchalk** [comment]
Looks like one type in this list - m2-PER-GM (under http://vocab.nerc.ac.uk/collection/P06/current/SMPG/) should be M2-PER-GM

**Comment by gwemon** [comment]
Thank you @stuchalk @dr-shorthair I have created these mappings. They have been queued for publication on the NVS shortly after 0730AM UT tomorrow 7th April.
