### ISSUE TITLE
NTR: Request for P06 Milligrams

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#19]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Milligrams <p><b>Definition</b><p> 10**-6 of the standard unit of mass (kilogram) or 10**-3 grams.<p><H2> Optional </H2><p><b>Synonym or acronym (AltLabel)</b><p> mg<p>

**Comment by dr-shorthair** [comment]
`owl:sameAs http://qudt.org/vocab/unit/MilliGM`

`sos:notation "mg"^^<http://qudt.org/schema/qudt/UCUMcs>`

**Comment by danibodc** [comment]
New P06 term has now been created:

MGRM - Milligrams
Description - 10^-6 of the SI unit of mass (kilogram) or 10^-3 grams.

It will be visible online after the database refresh from 1400UTC.

**Comment by danibodc** [comment]
Term now available on the NVS at http://vocab.nerc.ac.uk/collection/P06/current/MGRM/
