### ISSUE TITLE
NTR: Request for P06 kilometres per hour

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#22]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>kilometres per hour <p><b>Definition</b><p> number of kilometres (1000 metres) covered in an hour (60 minutes)<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/w/index.php?title=Kilometres_per_hour&oldid=989137259<p> <b>ORCID</b><p> https://orcid.org/0000-0001-6840-6785<p> <b>Synonym or acronym (AltLabel)</b><p> km h-1<p>

**Comment by dr-shorthair** [comment]
`owl:sameAs <http://qudt.org/vocab/unit/KiloM-PER-HR>`

`skos:notation "km.h-1"^^dt:UCUMcs` and `skos:notation "km/h"^^dt:UCUMcs`

**Comment by danibodc** [comment]
New term has now been created and is live on the NVS:

http://vocab.nerc.ac.uk/collection/P06/current/KMHR/

KMHR - Kilometres per hour

A change in location of a distance of one thousand metres in an elapsed time of one hour (3600 seconds).
