### ISSUE TITLE
New Term Request - grams per square metre per day (BODCNVS-963)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#25]
### Term name (PrefLabel)
grams per square metre per day
### Short name (AltLabel)
[Please enter the accepted abbreviation for the unit]
### Definition
grams per square metre per day
### Sources/references
http://qudt.org/vocab/unit/GM-PER-M2-DAY
Required for eReefs project

### Mapping to external terminologies
http://qudt.org/vocab/unit/GM-PER-M2-DAY
UCUM code: g/m2/d
### ORCID
0000-0002-3884-3420

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/P06/current/GSMD queued for publication on the NVS (next refresh 0730AM UT)
