### ISSUE TITLE
New Term Request - milligrams per square metre per second (BODCNVS-962)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#26]
### Term name (PrefLabel)
milligrams per square metre per second
### Short name (AltLabel)
[Please enter the accepted abbreviation for the unit]
### Definition
milligrams per square metre per second
### Sources/references
eReefs project

### Mapping to external terminologies
http://qudt.org/vocab/unit/MilliGM-PER-M2-SEC
UCUM code mg/m2/s

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/P06/current/MGSS queued for publication on the NVS (next refresh 0730AM UT)
