### ISSUE TITLE
New Term Request - milligrams per cubic metre per second (BODCNVS-961)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#27]
### Term name (PrefLabel)
milligrams per cubic metre per second
### Short name (AltLabel)
[Please enter the accepted abbreviation for the unit]
### Definition
milligrams per cubic metre per second
### Sources/references
eReefs project

### Mapping to external terminologies
http://qudt.org/vocab/unit/MilliGM-PER-M3-SEC
UCUM code mg/m3/s
### ORCID
0000-0002-3884-3420

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/P06/current/MGCS queued for publication on the NVS (next refresh 0730AM UT)
