### ISSUE TITLE
New Term Request - mole per square metre per day (BODCNVS-960)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#28]
### Term name (PrefLabel)
mole per square metre per day
### Short name (AltLabel)
[Please enter the accepted abbreviation for the unit]
### Definition
mole per square metre per day
### Sources/references
eReefs project

### Mapping to external terminologies
http://qudt.org/vocab/unit/MOL-PER-M2-DAY
UCUM code mol/m2/d
### ORCID
0000-0002-3884-3420

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/P06/current/MMSD queued for publication on 12/04/2021
