### ISSUE TITLE
New Term Request - micromoles per square metre (BODCNVS-975)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#29]
### Term name (PrefLabel)
micromoles per square metre
### Short name (AltLabel)
[Please enter the accepted abbreviation for the unit]
### Definition
micromoles per square metre
### Sources/references
eReefs project

### Mapping to external terminologies
http://qudt.org/vocab/unit/MicroMOL-PER-M2
UCUM code umol/m2
### ORCID
0000-0002-3884-3420

**Comment by gwemon** [comment]
https://vocab.nerc.ac.uk/collection/P06/current/UMSM queued for publication on the NVS (next refresh 0730AM UT)

**Comment by gwemon** [comment]
I am not closing this one yet because we seem to have an issue with the mapping to the QUDT term. It does not seem to have made it to the RDF triple store. @alko-k any idea why?

**Comment by gwemon** [comment]
@alko-k  FYI logged as Jira issue BODCWEBAPP-2304

**Comment by dr-shorthair** [comment]
QUDT OK now.
