### ISSUE TITLE
NTR : millimeters per year

### ISSUE THREAD

**Issue by whshannon** [nvs-vocabs/P06#3]
### Term name
millimeters per year 
### Short name
mm/year
### Definition
millimeters per year
### Sources/references
e.g. sedimentation rate; see dataset https://www.bco-dmo.org/dataset/763941

### Mapping to external terminologies
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]
### ORCID
http://orcid.org/0000-0002-9081-1004

**Comment by gwemon** [comment]
sorry @whshannon I had not seen your request. I'll send you the new code once it's on the NVS.

**Comment by gwemon** [comment]
created http://vocab.nerc.ac.uk/collection/P06/current/MMPY/
