### ISSUE TITLE
NTR: Milligrams per square metre per day per layer

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#31]
### Term name (PrefLabel)
Milligrams per square metre per day per layer
### Short name (AltLabel)
mg.m-2.d-1.{layer}-1
### Definition
Milligrams per square metre per day per layer
### Sources/references
eReefs

### Mapping to external terminologies
-
### ORCID
orcid.org/0000-0002-3884-3420

**Comment by gwemon** [comment]
@dr-shorthair what kind of process is this unit for? and what does the "per layer" represent?

**Comment by roy-lowry** [comment]
I was wondering about this one and was coming to the conclusion that it was embedding semantics into a unit of measure - back to the days of 'per milligram of wet sediment'. I'm pretty sure it wouldn't get into UDUnits.

**Comment by dr-shorthair** [comment]
Lets ask @markebaird @semmerson and @sharon-tickell

**Comment by dr-shorthair** [comment]
It is used for this: 
> Denitrification rate, specified per layer per m2 rather than per m3) so that the depth-integrated denitrification rate can be calculated by summing each layer without knowing the thickness of each layer (that varies with time).

**Comment by markebaird** [comment]
Hi all,

I agree this is a funny unit. In the model, denitrification is calculated for every model sediment layer (as a per m3 quantity). Most users want the denitrification rate of the whole sediment bed. However in our model the sediment layer thicknesses (there are typically 12 layers) varies with time, so calculating the whole flux per m2 would require the sum of (the flux per m3 multiplied by the layer thickness) for each of the 12 layers. This seemed too hard to do post-processing, so we gave the amount per layer so that the user can just sum the layers. In hindsight, for align with standard vocabularies, we should have stuck with per m3.

Mark

**Comment by gwemon** [comment]
Thank you @markebaird - do you intend to combine this unit with a P01 parameter code? If so then I think that it would be preferable to specify the "per layer" in the parameter description and keep the unit as a standard mg per m2 per day. We use the S02 vocabulary to capture this kind of information. See e.g. http://vocab.nerc.ac.uk/collection/S02/current/S02022/
So for example we could create a new S02 term for "per day per unit area per layer of the"  and combine this with the appropriate matrix term ([sediment](http://vocab.nerc.ac.uk/collection/S26/current/MAT00136/)), and substance ([dinitrogen](http://vocab.nerc.ac.uk/collection/S27/current/CS002756/)) and property ([production rate](http://vocab.nerc.ac.uk/collection/S06/current/S0600017/)) to give us a P01 parameter label of the form: e.g.
"Production rate of dinitrogen per day per unit area per layer of the sediment" and, to be unambiguous about the context of this parameter label, I would probably also recommend adding the S04 term "[model prediction](http://vocab.nerc.ac.uk/collection/S04/current/S041014/)" giving us:
Parameter label="Production rate of dinitrogen per day per unit area per layer of the sediment by model prediction"
Unit=http://vocab.nerc.ac.uk/collection/P06/current/UGDX/

Would that work?

**Comment by semmerson** [comment]
>
> Thank you @markebaird <https://github.com/markebaird> - do you intend to
> combine this unit with a P01 parameter code? If so then I think that it
> would be preferable to specify the "per layer" in the parameter description
> and keep the unit as a standard mg per m2 per day.
>

As I interpret the BIPM and NIST guidelines, that's exactly the right
approach.

**Comment by gwemon** [comment]
So our recommendation is to use the unit: http://vocab.nerc.ac.uk/collection/P06/current/UGDX/ for this quantity and migrate the information "per layer" in the parameter definition. I am closing this ticket but please feel free to reopen if needed.
