### ISSUE TITLE
NTR: Degrees Celsius weeks

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#32]
### Term name (PrefLabel)
Degrees Celsius weeks
### Short name (AltLabel)
DegC-week
### Definition
Degree heating weeks
### Sources/references
eReefs

### Mapping to external terminologies
http://qudt.org/vocab/unit/DEG_C-WK
### ORCID
orcid.org/0000-0002-3884-3420

**Comment by gwemon** [comment]
@danibodc see also https://coralreefwatch.noaa.gov/satellite/education/tutorial/crw24_dhw_product.php for explanation of this unit's usage.

**Comment by danibodc** [comment]
A new P06 code has now been created: DCWK	

**Preferred label:** Degrees Celsius weeks	
**Alternative label:** degC.wk	
**Description:** Temperature multiplied by time. Used to express temperature accumulation over the duration of a week, also known as Degree Heating Weeks.

This will be published live on the NVS from 0730 UTC tomorrow morning.
