### ISSUE TITLE
NTR: Square metres per second cubed

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/P06#33]
### Term name (PrefLabel)
Square metres per second cubed
### Short name (AltLabel)
m2.s-3
### Definition
Square metres per second cubed
### Sources/references
eReefs

### Mapping to external terminologies
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]
### ORCID
orcid.org/0000-0002-3884-3420

**Comment by danibodc** [comment]
A new P06 code has been created: SQM3

**Preferred label:** Square metres per second cubed	
**Alternative label:** m^2/s^3	
**Definition:** The SI unit of area, defined as a square of one metre long on each side, per cubic SI unit of time (seconds).

This will be published live on the NVS from 0730 UTC tomorrow morning.
