### ISSUE TITLE
NTR: Request for P06 Micromoles per minute per milligram

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#34]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Micromoles per minute per milligram <p><b>Definition</b><p> A unit for specific enzymatic activity giving the activity of an enzyme in quantity of product formed by the enzyme (micromoles) in a given amount of time (minute) per mass of total protein (milligram). The specific activity is equal to the rate of reaction multiplied by the volume of reaction divided by the mass of total protein. The SI unit for this quantity is katal/kg.<p><H2> Optional </H2><p><b>Sources/references</b><p> online resources<p> <b>Mapping to other terminologies </b><p> Related to: https://mdm.sandre.eaufrance.fr/node/283109<p>

**Comment by dr-shorthair** [comment]
Need an accompanying NTR for `unit:MicroMOL-PER-MilliGM-MIN` at https://github.com/qudt/qudt-public-repo/issues

**Comment by dr-shorthair** [comment]
UCUM code `umol/mg/min` or `umol.mg-1.min-1`

**Comment by JordanAthertonNOC** [comment]
One new P06 term created, anticipated to go live at ~07:00 GMT tomorrow.

UMGM [Micromoles per milligram per minute] (http://vocab.nerc.ac.uk/collection/P06/current/UMGM)
