### ISSUE TITLE
NTR: Request for P06 Grams per hectare

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#36]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Grams per hectare <p><b>Definition</b><p> A unit of mass per area equal to one part of 10**3  (thousand) of the SI unit of mass divided by 10**4 (10 thousands) times the SI unit of area.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1088<p> <b>Mapping to other terminologies </b><p> not yet in QUDT<p>

**Comment by dr-shorthair** [comment]
QUDT only has `unit:GM-PER-M2` Gram Per Square Metre so I suggest an accompanying NTR there https://github.com/qudt/qudt-public-repo/issues

**Comment by dr-shorthair** [comment]
UCUM code: `g/har` or `g.har-1`

**Comment by JordanAthertonNOC** [comment]
One new P06 term created, anticipated to go live at ~07:00 GMT tomorrow.

GPHT [Grams per hectare] (http://vocab.nerc.ac.uk/collection/P06/current/GPHT)
