### ISSUE TITLE
NTR: Request for P06 Nanograms per millilitre

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#37]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Nanograms per millilitre <p><b>Definition</b><p> A unit of mass concentration equal to 10**-12 of the SI unit of mass (kilogram) divided by 10**-6 of the SI unit of volume (litre).<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1088<p> <b>Mapping to other terminologies </b><p> not yet in QUDT<p>

**Comment by dr-shorthair** [comment]
QUDT has 
- `unit:NanoGM-PER-L` Nanograms per litre
- `unit:NanoGM-PER-M3` Nanogram Per Cubic Metre 
- `unit:NanoGM-PER-MicroL` Nanograms per microlitre 

So I suggest an accompanying NTR request there https://github.com/qudt/qudt-public-repo/issues

**Comment by dr-shorthair** [comment]
UCUM code  `ng/mL` or `ng/ml` or `ng.mL-1` or `ng.ml-1`

**Comment by JordanAthertonNOC** [comment]
One new P06 term created, anticipated to go live at ~07:00 GMT tomorrow.

NGML [Nanograms per millilitre] (http://vocab.nerc.ac.uk/collection/P06/current/NGML)
