### ISSUE TITLE
NTR: Request for P06 Grams per litre

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#38]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Grams per litre <p><b>Definition</b><p> A unit of mass concentration equal to 10**-3 the SI unit of mass (kilogram) divided by the SI unit of volume (litre).<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1088<p> <b>Mapping to other terminologies </b><p> http://qudt.org/vocab/unit/GM-PER-L<p>

**Comment by dr-shorthair** [comment]
See http://qudt.org/vocab/unit/GM-PER-L

**Comment by dr-shorthair** [comment]
UCUM code `g/L` or `g/l` or `g.L-1` or `g.l-1`

(In UCUM both `L` and `l` are valid symbols for litre.)

**Comment by JordanAthertonNOC** [comment]
One new P06 term created, anticipated to go live at ~07:00 GMT tomorrow.

GPRL [Grams per litre] (http://vocab.nerc.ac.uk/collection/P06/current/GPRL)
