### ISSUE TITLE
NTR: Request for P06 Cubic micrometres per litre 

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#39]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Cubic micrometres per litre  <p><b>Definition</b><p> A unit of volume fraction used to express the biovolume of cells in suspension in a liquid and equal to one part in 10**18 over one part in 10**3 of the SI unit of volume (cubic metre). <p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1088<p> <b>Mapping to other terminologies </b><p> Not yet in QUDT<p>

**Comment by dr-shorthair** [comment]
QUDT has
- `unit:MicroM3-PER-M3` Cubic microns per cubic metre
- `unit:MicroM3-PER-MilliL` Cubic microns per millilitre

So I suggest an accompanying NTR there as well

**Comment by dr-shorthair** [comment]
UCUM code: `um3/L` or `um3/l` or `um3.L-1` or `um3.l-1`

**Comment by JordanAthertonNOC** [comment]
One new P06 term created, anticipated to go live at ~07:00 GMT tomorrow.

CUPL [Cubic micrometres per litre] (http://vocab.nerc.ac.uk/collection/P06/current/CUPL)
