### ISSUE TITLE
NTR: Request for P06 Grams per square kilometre

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/P06#40]
### Term name (PrefLabel)
Grams per square kilometre
### Short name (AltLabel)
gr / km^2
### Definition
10^-3 of the SI unit of mass (kilogram) over the square of one thousand standard unit of length (metre). 
### Sources/references
see eg. controlled vocab for kilogram per square kilometre: http://vocab.nerc.ac.uk/collection/P06/current/KGAK/

**Comment by JordanAthertonNOC** [comment]
One new P06 term created, anticipated to go live at ~07:00 GMT tomorrow.

GPKM [Grams per square kilometre] (http://vocab.nerc.ac.uk/collection/P06/current/GPKM)
