### ISSUE TITLE
NTR: Request for micrograms carbon per litre (BODCNVS-1652)

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/P06#43]
### Term name (PrefLabel)

Micrograms of carbon per litre

### Short name (AltLabel)

ug C/L

### Definition

10^-6 grams or one 10^-9 of the SI standard unit of mass (kilogram) of carbon per litre.

### Sources/references

https://vocabs.ceh.ac.uk/cast/en/page/304

**Comment by danibodc** [comment]
Hi @timvdstap thanks for this request.

I believe we try to keep the object of interest (in this case Carbon) independent from the units of measure. The carbon would be expressed in the associated P01 parameter code e.g. 'Concentration of carbon...'

I would therefore recommend using 'Micrograms per litre': http://vocab.nerc.ac.uk/collection/P06/current/UGPL/

**Comment by timvdstap** [comment]
Hi @danibodc -- thank you that makes sense, I think that indeed is the best approach to take!
