### ISSUE TITLE
NTR: cells per millilitre (BODCNVS-1650)

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/P06#45]
## Required

I'm not entirely sure if this is the best way to approach this.

### Term name (PrefLabel)

cells per millilitre

### Short name (AltLabel)

cells/ml

### Definition

A unit of cell concentration expressed in cells per unit of volume equal to one millilitre. 

### Sources/references

https://www.tititudorancea.com/z/cells_per_milliliter.htm

**Comment by danibodc** [comment]
Hi @timvdstap many thanks for your request.

I would perhaps suggest using 'Number per millilitre': http://vocab.nerc.ac.uk/collection/P06/current/UCML/ 

Would this work for you?

**Comment by timvdstap** [comment]
Hi @danibodc I think that could work, in the parameter description I will just have to make sure then that 'number' reflects the count of cells. I saw that URI but wasn't sure whether there would perhaps be a need for a more specific one.

**Comment by gwemon** [comment]
Hello @timvdstap what is/are the parameter(s) that will be associated with this unit @timvdstap? Are these from flow cytometric analysis of water samples?

**Comment by timvdstap** [comment]
Hi @gwemon Yes exactly, this would be for flow cytometry data.

**Comment by roy-lowry** [comment]
As a principle of good metadata practice, units of measure should not contain semantic information such as what is being measured in a measurement. So I would strongly support @danibodc suggestion. Any clarification of the meaning of 'number' that is required belongs in parameter description (P01).
