### ISSUE TITLE
NTR: Request for P06 Cubic millimetres (BODCNVS-1743

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#46]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Cubic millimetres <p><b>Definition</b><p> A unit of volume defined as a cube 1 millimetre long on each edge.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://qudt.org/vocab/unit/MilliM3<p>

**Comment by danibodc** [comment]
Related to https://github.com/nvs-vocabs/P01/issues/198

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/P06/current/CMM3/
