### ISSUE TITLE
NTR: Request for P06 Number per 100 millilitres (BODCNVS-1232)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P06#48]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Number per 100 millilitres <p><b>Definition</b><p> Count of an entity or phenomenon occurrence in one part in 10^6 of the SI unit of volume (cubic metre).<p><H2> Optional </H2><p><b>Sources/references</b><p> Similar to http://vocab.nerc.ac.uk/collection/P06/current/NBHG/<p>

**Comment by jakjonbodc** [comment]
Created P06 term NBTM - Number per 100 millilitres. Closing issue
