### ISSUE TITLE
NTR : New record needed for units of tonnes

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P06#5]
### Term name
Tonnes
### Short name
t
### Definition
A non-SI unit of mass equivalent to 1000 SI unit of mass (kilogram).
### Sources/references
[Please enter a link to a reference source]

### Mapping to external terminologies
[Is your submission related to any existing terms in external resources: please enter one or a list of URIs]

**Comment by dr-shorthair** [comment]
See also http://qudt.org/vocab/unit/TON_M

**Comment by gwemon** [comment]
Thank you @dr-shorthair. I will add a link to the QUDT term.

**Comment by gwemon** [comment]
Term and mappings added to the NVS, see: http://vocab.nerc.ac.uk/collection/P06/current/MTON/
