### ISSUE TITLE
NTR: Request for P06 Numbers per hectare

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P06#9]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Numbers per hectare <p><b>Definition</b><p> Count of an entity or phenomenon's occurrence in one 10,000th of the SI unit area (square metre).<p><H2> Optional </H2><p>

**Comment by dr-shorthair** [comment]
> Count of an entity or phenomenon's occurrence in one 10,000th of the SI unit area (square metre).

Count of an entity or phenomenon's occurrence in 10,000 times the SI unit area (square metre).

**Comment by gwemon** [comment]
Thank you for the correction @dr-shorthair. 
The new units has been added to the NVS at http://vocab.nerc.ac.uk/collection/P06/current/HCTR
and mapped to QUDT http://qudt.org/vocab/unit/HA
It will be published at 1300UTC today
